version: '3.8'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoSecure?
    volumes:
      - 'mongodb_data:/data/db'

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoSecure?
      ME_CONFIG_MONGODB_URL: mongodb://root:MongoSecure%3F@mongo:27017/

volumes:
  mongodb_data: {}
