import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { UserProvider } from '@auth0/nextjs-auth0/client';

import '@styles/globals.scss';
import { cn } from '@/lib/utils';
import { NavBar } from '@/components/NavBar';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UserProvider>
      <html lang="en">
        <body className={cn('min-h-screen bg-background font-sans antialiased', inter.variable)} suppressHydrationWarning={true}>
          <NavBar />
          {children}
        </body>
      </html>
    </UserProvider>
  );
}
